<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>xUnit1008</NoWarn>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LambdaTale.v3\LambdaTale.v3.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="testconfig.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
